image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv

before_script:
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
    - python3 -m unittest discover ./src/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual